---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader 
  labels:
    name: production
    app: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  url: https://stakater.github.io/stakater-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  releaseName: reloader
  targetNamespace: reloader
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 3m

